export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'




export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART'
export const PRODUCT_REMOVED_TO_CART = 'PRODUCT_REMOVED_TO_CART'
export const ALL_PRODUCTS_REMOVED_TO_CART = 'ALL_PRODUCTS_REMOVED_TO_CART'




export const ADD_FILTERS = 'ADD_FILTERS'
export const ADD_SEARCH = 'ADD_SEARCH'